use_frameworks!

target 'ADSRouter_Example' do
  pod 'ADSRouter', :path => '../'

  target 'ADSRouter_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
